name: Helm Chart Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  chart-release:
    name: Create and Publish Chart Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Add bitnami repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Run chart-releaser
        uses: ./.github/actions/chart_releaser
        with:
          config: .github/actions/chart_releaser/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
