name: Controller Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build, Lint, Unit + Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install --no-cache-dir poetry==2.4.1
          poetry install --no-root
      - name: Lint with ruff
        working-directory: ./oidc-controller
        run: |
          poetry run ruff check .
      - name: Format with ruff
        run: |
          poetry run ruff format --check oidc-controller
      - name: Unit tests
        run: |
          poetry run pytest -m "not e2e and not integration" --log-cli-level=INFO --cov --cov-report lcov
      - name: Integration tests
        run: |
          poetry run pytest -m integration --log-cli-level=INFO
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          flag-name: python-${{ matrix.python-version }}
          parallel: true
  code-coverage:
    name: Generate Code Coverage
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          parallel-finished: true
          carryforward: "python-3.13"
