name: Controller Unit Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build, Lint, Unit + Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install --no-cache-dir poetry==2.3.2
          poetry install --no-root
      - name: Format with ruff
        run: |
          poetry run ruff format --check oidc-controller
      - name: Unit tests
        run: |
          poetry run pytest -m "not e2e and not integration" --log-cli-level=INFO --cov --cov-report lcov
      - name: Integration tests
        run: |
          poetry run pytest -m integration --log-cli-level=INFO
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          flag-name: python-${{ matrix.python-version }}
          parallel: true
  code-coverage:
    name: Generate Code Coverage
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          parallel-finished: true
          carryforward: "python-3.13"
